Opb64 12bits
hbs/warp10-platform pull request #11
Opened 2022-05-23 21:56 UTC by pi-r-p

proposal to speed up OPB64 encoding (only from byte[] to byte[] for the moment, other functions not affected).

It speeds things up on my test computer, factor 2. But it needs to be tested on other CPU.

2022-05-24 05:37 UTC, hbs requested changes

2022-05-24 05:37 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/OrderPreservingBase64.java
> +import com.google.common.primitives.Bytes;
why is this import needed?

2022-05-24 05:37 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/OrderPreservingBase64.java
> +    // also build a 12bit lut. Encoding per 12bits double speed. (now reaching 30MB/s)
lut -> look up table. Explain how the table is built so the actual encoding is easier to understand.

2022-05-24 05:37 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/OrderPreservingBase64.java
> +      o = ((((data[i]) << 4) | ((data[i + 1] & 0xFF) >>> 4)) << 1) & 0x1FFF;
Explain how the index is computed, the final left shift by 1 is only obvious if you know how the look up table is built, which so far is not described.

The computation could be simplified into"

(data[i] << 5 | ((data[i + 1] & 0xF0) >>> 3)) & 0x1FFF

2022-05-24 05:37 UTC, hbs commented on crypto/src/main/java/io/warp10/crypto/OrderPreservingBase64.java
> +      o = ((((data[i + 1]) << 8) | ((data[i + 2] & 0xFF))) << 1) & 0x1FFF;
shouldn't data[i + 1] be shifted 9 bits to the left instead of 8? There will be an overlap with the MSB of data[i + 2] which is shifted by 1

2022-06-09 12:55 UTC, pi-r-p commented
It is more efficient to merge hbs:opb64.opt , then to update unit tests, then I will do another PR on the main branch.

2022-06-09 12:55 UTC, closed without merging